services:
  user-service:
    build: .
    container_name: user-service-dev
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  mailhog:
    image: mailhog/mailhog:latest
    container_name: user-service-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

